### ISSUE TITLE
Save Passwords in a file

### ISSUE THREAD

**Issue by kzelda** [AlessandroZ/LaZagne#10]
Add -o Option to save the output in a file

**Comment by reversingfr** [comment]
normally you can already do it with the option -w

lazagne.exe all -w

**Comment by kzelda** [comment]
Not work :-1: 
laZagne.exe all -w c:\apps\pass2.txt

**Comment by kzelda** [comment]
Thx it works , but iwant to specify a file path

**Comment by AlessandroZ** [comment]
At the begining, I wanted to specify the file path to save the file but I changed my mind when I developed the Firefox module. 

Many advanced options are done when a masterpassword is set on Firefox. Set a masterpassword on it, and you will see it : https://support.mozilla.org/en-US/kb/use-master-password-protect-stored-logins

If a masterpassword is set, a dictionnary attack is realized using a list of 500 famous passwords, if it is not find yet, it will do a bruteforce attack on 3 characters (to found easy password like "abc") and to finish, it will test your passwords found on other application (if you use the same password in pidgin and as a masterpassword, it will found it). 
So if you choose to save the output and the masterpassword has not been find after all of theses attacks, 2 files (keys3 and signons or logins files) are stored on the result directory in order to perform the bruteforce attack offline. 

All these features are not explicitly described in the readme. However, that is the why I need to store the result on a directory and not only on a file. 
So, it could be possible to add a feature to specify the file path but it will like that: 
```
lazagne.exe all -w C:\Users\<USER>\NewDir
```
"NewDir" will be a new directory (a not existing one) which will be created. It is not really clear for users to specify a new directory and not a text path. I don't know if it is a good idea.

**Comment by kzelda** [comment]
:+1:  Thank you very much

**Comment by DrZMarco** [comment]
I've tried with -w & -o, but noone of this work to save output password in a file.  Wich parameter i've to write?

**Comment by Eyremba** [comment]
> I've tried with -w & -o, but noone of this work to save output password in a file. Wich parameter i've to write?

Why you don't just use `lazagne.exe all > output.txt` ?

**Comment by dhsagar123** [comment]
How To Use - Chats Option
