### ISSUE TITLE
More application support: Putty, WinSCP, FileZilla etc.

### ISSUE THREAD

**Issue by CaledoniaProject** [AlessandroZ/LaZagne#119]
Hi, 

Can you kindly add support for the following softwares?
WinSCP, PuTTY, SuperPuTTY, FileZilla, and Microsoft Remote Desktop

I'd like to see LaZagne include all features of SessionGopher:
https://github.com/fireeye/SessionGopher

**Comment by AlessandroZ** [comment]
Hi, 
Most of these softwares are already supported ([here](https://github.com/AlessandroZ/LaZagne/tree/master/Windows/lazagne/softwares/sysadmin)) except SuperPuTTy and Microsof Remote Desktop (this one is quite difficult because rdp files do not have default location so except doing a research on the entire disk is difficult to be sure that a file exists or not, but I will do it on some commun repository).

**Comment by CaledoniaProject** [comment]
Awesome

**Comment by basketas** [comment]
For RDP, this is possible:
https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/credentials/rdc_manager_creds.rb

**Comment by AlessandroZ** [comment]
I have added a new module to manage the RDP Connection manager [tool](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/sysadmin/rdpmanager.py). 

For SuperPutty, I have installed it but I have never managed to save a password. So I don't know if it's still possible using the last version. Even SessionGopher do not talk about password on the superputty [function](https://github.com/fireeye/SessionGopher/blob/master/SessionGopher.ps1#L829). 

If you get a way to do it, tell me and open the issue again.
