### ISSUE TITLE
Try to extract infos from all accessible users

### ISSUE THREAD

**Issue by alxchk** [AlessandroZ/LaZagne#121]
In case if security context is something like SYSTEM or root, LaZagne can access data of all users. Currently paths and communication points are hardcoded as ~, so there is sad situation, when you need to change user to make LaZagne works.

Also there may be situations when access rights to some user accounts (or folders, or sockets) may be incorrect, so even non-root user can access this information.

**Comment by AlessandroZ** [comment]
On Windows host, if you have system or high privilege (admin with UAC bypassed), user tokens are impersonated to be in the same context as the user, so credentials could be retrieved easily. 

However, on linux host, it has not been implemented yet. I think you're taking about Linux host because hardcoded path using "~" are present only on linux (or Mac). I will try to do it when I can. 

On Windows, depending on our privileges, particular modules are launched. For example, Windows hashes will only be retrieved with high privileges.
I wanted to do it using the same method on Linux but I won't check folder misconfigurations, so I won't check if a non-root user could access to these information. I have never been in this case, but if you have seen this before, I could do it.
