### ISSUE TITLE
Metasploit support

### ISSUE THREAD

**Issue by basketas** [AlessandroZ/LaZagne#123]
This is not an issue, but rather a request.. It would be very useful to implement Lazagne as a metasploit module. However, Metasploit uses Ruby, but ReflectiveDLLinjection is possible as a method to execute Lazagne..

**Comment by AlessandroZ** [comment]
I will be happy to see LaZagne as a post exploitation module on metasploit. However, I won't work on it because I already embed this tool in another project called [pupy](https://github.com/n1nj4sec/pupy/). The python code is interpreted on the victim host and no files are written to the disk. I recommend to check this awesome project. 

I'm already working on this project, so I won't do the same thing for metasploit (but if someone add it to metasploit for me, I will be happy too).

**Comment by AlessandroZ** [comment]
Moreover, using pupy, credentials retrieved from lazagne are stored locally on a database and could be seen using the "creds" module (as metasploit does).

**Comment by basketas** [comment]
There is a module in Metasploit :
post/windows/manage/reflective_dll_inject

So, if Lazagne could be made into a reflective DLL somehow, that would be all that's necessary.
