### ISSUE TITLE
Issue running standalone against  Windows .NET Server (Build 3790, Service Pack 1)

### ISSUE THREAD

**Issue by 0p1um** [AlessandroZ/LaZagne#133]
Hello, 
First of all, i want to congrat you for youre script, it is awesome ! 
The standalone work against my W10 machine, but against a box using Windows .NET server i get some errors : 

> C:\Documents and Settings\joe\Desktop>laZagne.exe all
> laZagne.exe all
> Traceback (most recent call last):
>   File "laZagne.py", line 17, in <module>
>   File "C:\Users\joe\Desktop\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
>   File "lazagne\config\changePrivileges.py", line 3, in <module>
>   File "C:\Users\joe\Desktop\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
>   File "lazagne\config\WinStructure.py", line 330, in <module>
>   File "ctypes\__init__.py", line 435, in __getattr__
>   File "PyInstaller\loader\pyiboot01_bootstrap.py", line 169, in __init__
> __main__.PyInstallerImportError: Failed to load dynlib/dll 'vaultcli'. Most probably this dynlib/dll was not found when the application was frozen.
> Failed to execute script laZagne

I am connected to this box by using a meterpreter with system privileges.

> meterpreter > shell
> Process 1440 created.
> Channel 5 created.
> Microsoft Windows [Version 5.2.3790]
> (C) Copyright 1985-2003 Microsoft Corp.
> C:\WINDOWS\system32>whoami
> whoami
> nt authority\system

Thanks for reading.

**Comment by AlessandroZ** [comment]
This issue is well known and I cannot found a good solution. It happen only using the executable file. I build it using pyinstaller and some version of Windows cannot run it. 

However, the best way to use it on all windows is using the [pupy](https://github.com/n1nj4sec/pupy/) project. Lazagne has been added has a post exploitation module. The python code will be interpreted in memory so you should not need to write the exe file on the disk anymore.
