### ISSUE TITLE
error version 2.2 LaZagne 

### ISSUE THREAD

**Issue by wilkin07** [AlessandroZ/LaZagne#150]
Sorry, I do not speak English at birth, the problem I'm having is the following with LaZagne version 2.2, version 2.1 works bn but version 2.2. has the following error, "Program too big to fit in memory" that is the error.
this error in windows 10.

greeting

**Comment by AlessandroZ** [comment]
I have never had this error, however, if the problem persists, I suggest you to try to launch lazagne using pupy (https://github.com/n1nj4sec/pupy/). Lazagne has been embedded as a post exploitation module. 
Otherwise, try to compile lazagne  yourself, maybe it could be solve the problem (I'm not sure of that).
