### ISSUE TITLE
Psutil?

### ISSUE THREAD

**Issue by 9268** [AlessandroZ/LaZagne#152]
`Traceback (most recent call last):
  File "laZagne.py", line 117, in launch_module
  File "lazagne\softwares\memory\memorydump.py", line 72, in run
  File "site-packages\psutil\__init__.py", line 364, in __init__
  File "site-packages\psutil\__init__.py", line 404, in _init
NoSuchProcess: psutil.NoSuchProcess no process found with pid 712`

![1](https://user-images.githubusercontent.com/25134502/30581225-ff9e6970-9d51-11e7-8802-b0eb47dc2453.png)

Bad english,don't mind
The problem I'm having is in the latest version 2.2 you releasesed, this error in windows 10,i run it as admin in cmd,it takes a lot time before Traceback show,
and one of password make me confused
I installed anaconda2.7 in my computer,i run your source code but import err
![2](https://user-images.githubusercontent.com/25134502/30581895-5897114c-9d54-11e7-81a4-2d540955896c.png)
it surely not a module named 'memorpy.py' in project
after all ,do you have effective ways to defend such kinds of software?

**Comment by AlessandroZ** [comment]
To compile the project, you should install all requirements needed. Follow the [wiki ](https://github.com/AlessandroZ/LaZagne/wiki/Requirements). 
`pip install https://github.com/n1nj4sec/memorpy/archive/master.zip`

I took time to execute because the version 2.2 crawl browsers memory to find passwords. So depends on the memory size of the process, it could be extremely long. That's why I decided to comment this feature for the next release (2.3). Close all browsers (firefox, ie, chrome, etc.) and launch the tool again, it should be executed faster. 

To answer your last question, I recommend using a password manager to store all your passwords. Only keepass is managed by lazagne so try another password manager (1Password, Enpass, etc.).
