### ISSUE TITLE
-drive parameter still checks local system

### ISSUE THREAD

**Issue by w3aryb0arpig** [AlessandroZ/LaZagne#156]
Using version 2.3 of the Python code, the _-drive_ parameter works great and is excellent. Nonetheless, it still checks the local system on which you are running the Python code as well as the external drive.

So, if I run _python laZagne.py all -drive E_ for example, it returns passwords from the E drive as well as the local drive (C drive).

I am unsure if this is intentional or not but it can cause confusion not knowing which drive the passwords are on.

**Comment by AlessandroZ** [comment]
The problem is that some credentials are retrieved from registry. I have limited some checks to get less passwords from localhost in the new release (2.3.1), but you will still see some of them such as LSA secrets, vault, etc. 
It will be possible to print only what you want, I should add some checks to not print all registry module but I don't have enough time to do it.
