### ISSUE TITLE
Blank password

### ISSUE THREAD

**Issue by fightforge** [AlessandroZ/LaZagne#158]
Many times i get this output:
Password Found !!!
URL: http://....
Login: 
Password:

and nothing else.
What could be?

Thanks

**Comment by AlessandroZ** [comment]
I cannot help you without any explanation. Which OS are you using ? Which password are you talking about ? The module used ? Are you sure, a password exits and it's not the browser that keep a blank password ? 

Then, when I will be sure that the problem come from lazagne, I could correct it.

**Comment by middlestreetwalker** [comment]
I have the same issue
URL:facebook.com
Login: name
Password:

Iam using windows 10. I used the all module

**Comment by Deathlive** [comment]
If the password is not saved in browser, then it is not displayed.

**Comment by middlestreetwalker** [comment]
thanks for clearing that up

**Comment by AlessandroZ** [comment]
The problem is not cleaning the empty password (which is easy to do) but to understand why there are empty passwords. 

Which module is affected ? (the module "all", launch all modules so it does not help me, try launching browsers module with some options to detect which one fails, such as firefox, ie, etc). 

When you know the browser impacted try to know if it's the decryption process that fails. List passwords saved for this browser using the GUI ([firefox](https://www.howtogeek.com/111555/view-and-delete-stored-passwords-in-firefox/), [chrome](http://www.thewindowsclub.com/manage-view-saved-passwords-chrome), etc.). 

When you saw your passwords, find your empty password using the login. If this login is well associated with an existing password that lazagne does not retrieved, there is a problem in lazagne, and you can say that the process descryption fails. Launch lazagne in debug mode with the -vvv option, try to see if there is an error. 

I cannot reproduce the problem, so right now I cannot help you but you can help me to debug the issue. 

Thanks

**Comment by Amm2100** [comment]
I have the same problem ,

Windows : 10 
Chrome 
I ran only Browsers
output : 
Password found !!!
URL: https://www.facebook.com/login.php
Login: 
Password: 
as I double checked my browser to see the password and I saw my passwords

**Comment by Amm2100** [comment]
I have the same problem ,

Windows : 10
Chrome
I ran only Browsers
output :
Password found !!!
URL: https://www.facebook.com/login.php
Login:
Password:
as I double checked my browser to see the password and I saw my passwords

**Comment by AlessandroZ** [comment]
Wifi passwords have been corrected but not blank passwords. 
I think the problem is related to this issue: https://github.com/AlessandroZ/LaZagne/issues/183

I could not reproduce the issue, so it's difficult to debug. If someone could do it for me, it would be nice.
