### ISSUE TITLE
Windwos XP not working.

### ISSUE THREAD

**Issue by Deathlive** [AlessandroZ/LaZagne#175]
Why does not it work for Windows XP ?
Libraries do not support or what else.

**Comment by AlessandroZ** [comment]
At the beginning, I did some tests on XP but now I do not realize any tests on it. However, it should work. If it does not work as you said, what's the problem ? 

The problem comes from a module ? Or the tool cannot be launched ? 

If it cannot be launched, it does not mean that it does not work but you should compile it again to work on this system.
