### ISSUE TITLE
Upgrade construct version

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#237]
Hi!

I would really like to integrate LaZagne into a project I'm trying to do, but I'm using a newer version of construct (the most recent version - 2.9.45). Is it possible to remove the "==2.9.39" in the requirement.txt file? (I'm not sure if any modification is required in the code).

Thanks!

**Comment by AlessandroZ** [comment]
Hi, 

To use lazagne as an external lib is quite easy. You should import the lib, call the function "[runLaZagne](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/laZagne.py#L263)" and then print passwords found on your own tool because all passwords found are returned from this function using [yield](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/laZagne.py#L313). 

Lazagne has been embeed to pupy, check it how it has been done: https://github.com/n1nj4sec/pupy/blob/unstable/pupy/modules/lazagne.py#L72 

I can change to a newer version of construct, but I has to be sure first everything will work fine (and right now I have no time to take care of that, sorry).

**Comment by eranzim** [comment]
Yes, my code is very similar. On my machine I have the newer construct (2.9.45), and it works for me (though I didn't run any "tests", just a normal run of the windows code). I wanted to add LaZagne's `requirement.txt` as additional requirements to my project (by adding a `-r ..\path\to\requirement.txt` line to my own requirements file, as explained [here](https://stackoverflow.com/a/11704396/855395)), but my project uses 2.9.45, so pip doesn't allow me to have 2 different versions of construct in a single pip install statement.

I understand you wish to check everything works properly before you upgrade, of course. I wouldn't expect otherwise. I currently have a workaround, so whenever you get to it - that would be fine, thanks!

**Comment by AlessandroZ** [comment]
construct has been removed.
