### ISSUE TITLE
Bitcoin Private Key recovery

### ISSUE THREAD

**Issue by devcoinfet** [AlessandroZ/LaZagne#265]
Hey Alessandro, Hows things?
The reason for the inquiry is I have some code I wrote I don't code malware so I cant release it as such.
I was wondering if You would be interesting in merging private key recovery off of drives and clipboards
not the type of code that can replace it with ours just recover

If you deny the request I may just build a .net app in c# to wrap the python as an executable and make it a standalone recovery program for corrupted hard drives that wont boot.

This is me asking is that going to far with this tool or is it in your scope of legit enough to include

**Comment by AlessandroZ** [comment]
Hi, 
How do you retrieve the private key ? If it's not stored on the disk but it's from the clipboard, I won't add it because it needs an action from the user. I try to dump all passwords from filesystem or dumping a process memory. 
If I don't understand well, I will be interested to see where the private key is stored. 

`If you deny the request I may just build a .net app in c# to wrap the python as an executable and make it a standalone recovery program for corrupted hard drives that wont boot.`
How to you wrap the python code to C# ? 
And for hard drives that won't boot, you can use https://github.com/AlessandroZ/LaZagneForensic

Have a nice day

**Comment by devcoinfet** [comment]
I'm using personal methods I wrote to extract the private keys from files on the system.  What I do is traverse every file of a certain extension on all drives and have it parse it line by line and split those lines into individual lines to extract a 51 byte private key than I convert to WIF

**Comment by devcoinfet** [comment]
and the clipboard thing requires no user interaction and its pure python and if I did wrap it I would store the compile python exe as a resource in visual studio than extract it to use it on the drives etc but its pure python

**Comment by AlessandroZ** [comment]
Retrieving the clipboard is not on the scope of the project 's goal (retrieving passwords), so I won't add it. 
However, for the bitcoin private key, it seems interesting, but I don't want to check all files (it takes too long). 
I will be ok if you check only for some paths (user's desktop, home, Documents, etc.) and if you don't use any external libs on your module. Otherwise, I'm sorry, I could not add it. 

Thanks for your time, have a nice day.

**Comment by KiUserExceptionDispatcher** [comment]
There is no reason to add private key's grabber in this project because they are useless without password which is not stored anywhere.

**Comment by AlessandroZ** [comment]
Sorry @devcoinfet, I agree too. I close the issue, but thanks for your feedback. If you have other ideas, don't hesitate to come back. 
Have a nice day !!
