### ISSUE TITLE
Running from PyCharm finds more passwords

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#268]
When running from cmd (tried normal, elevated and system cmd's), Lazagne finds less passwords compared to when I run it from PyCharm running as system. Running with all -vvv.
I see a difference in Pypykatz, Credman and Windows modules.
I also see a difference that I suspect causes this - in PyCharm I see a few `[+] System masterkey decrypted for ...` lines at the beginning. Why does this not appear in cmd?

**Comment by AlessandroZ** [comment]
The problem is I cannot debug your problems without any debug done by yourself. 

You should done some debug, launch process explorer, check the integrity level of pycharm (if you see "system masterkey", you should have high privilege), check the user used by pycharm, compare debug output with -vv in pycharm and with cmd (using the same level of integrity with these two bins), redirect the entire output to a file to compare it easily (python lazagne.py all -vv > test.txt). 

Check if there are other differents between pycharm and cmd (both are x86 / x64 bits, etc..). 

Do prints inside my code to found where the problem occurs, etc.

**Comment by eranzim** [comment]
It's a bitness issue (PyCharm was running it with 64-bit python). When I run it now from a system cmd, it decrypts the system masterkeys with 64-bit but not with 32-bit python.

**Comment by AlessandroZ** [comment]
Pypykatz reads lsass.exe process memory, it could not be done by a x86 bit process on x64 bit system. That's the difference. This is not an error.
