### ISSUE TITLE
Win 8.1 64bit standalone not working.

### ISSUE THREAD

**Issue by fakerli** [AlessandroZ/LaZagne#30]
It says the .exe isnt working on 64bit systems.

**Comment by AlessandroZ** [comment]
I have done some tests on Win8.1 64 bit and I worked well. However, you are not the only one who has this error. 

You could see theses issues to have more information: 
- https://github.com/AlessandroZ/LaZagne/issues/15
- https://github.com/AlessandroZ/LaZagne/issues/23

It seems to be a problem on how to compile the project but I cannot understand the problem because I cannot reproduce it.
