### ISSUE TITLE
it cant decrypt CRED_TYPE_DOMAIN_PASSWORD in windows

### ISSUE THREAD

**Issue by byehack** [AlessandroZ/LaZagne#365]

**Comment by AlessandroZ** [comment]
What's the problem with CRED_TYPE_DOMAIN_PASSWORD ?

CRED_TYPE_DOMAIN_PASSWORD are stored in Windows Credentials files. To decrypt these files, you will need windows password user, if lazagne does not found the correct password, no files could be decrypted. Otherwise, domain passwords should be well decrypted. 

If you have in your output `ok for masterkey...`, you should be able to decrypt it.
