### ISSUE TITLE
editing source, compiling and still being labeled as trojan

### ISSUE THREAD

**Issue by nickrh75** [AlessandroZ/LaZagne#366]
Hi, thanks for the great recovery tool.
I have edited the laZagne.py file considerably, changing order, names, adding inocuous calculations etc, but the compiled .exe is still being blocked by cpanel's AV, so I can't upload it. Have also compiled it with an alternative to pyinstaller, the .exe works but is also blocked...
Should I also try to edit the config files as well, or go for a deeper edit of laZagne.py? Sorry, I know this is something one should learn by himself, but I am not experienced enough and any tips or general pointers on how to change the signature of the .exe would be greatly appreciated.
Cheers, nick

**Comment by byehack** [comment]
the blocking is for some dlls lazagne using.

**Comment by nickrh75** [comment]
Hmm but where should I try to edit in order avoid being blocked? any specific function of laZagne.py? Any general help to go in the right direction greatly appreciated, no need to spill all the beans :)

**Comment by byehack** [comment]
are you convert it to exe?

**Comment by 0E800** [comment]
Try using an older version. you know, like before everyone wanted to try it and brown-nosing infosec assholes created IOCs and other identifying features that ultimately made it to antivirus applications.

You need to learn python like water makes its way to the ocean (trial and error) and compile your own from scratch. Through trial and error, identify how your antivirus product is identifying it to be malware.
Most likely its a hash but it could be that the antivirus application monitors the folders being affected or the use of python. There could be a combination of factors. 

Convince dev to create a build script that applies salts or other various methods of obscuring the compiled build so that every time its built, it no longer matches the static indicators of compromise.
Which is really the best option for software like this.

Have a build script, and a script that obfuscates the code or arranges the functions etc. before compiling.

Making users build it first is also a Cover Your Ass clause. For the same reasons why Guns are not sold already loaded with ammunition.

Food for thought.

**Comment by nickrh75** [comment]
Thanks for your answer @0E800 , yes there's a lot to consider and (in my case) to learn.
I tried splitting the .exe into incrementanlly bigger blocks, from 0 to byte 256, then from 0 to 512 and so on, all the way to the full file. But none of the blocks get flagged, only the full file, which leads me to conclude the AV is considering what the program does, not how it's written, please correct me if I'm wrong.

**Comment by 0E800** [comment]
I am going to try my own tests.

Experiment with app virtualization like thinapp. Not sure if its possible
to create a thinapp from a python script, but I'll try.

Possibly the python script can be encapsulated within a powershell or batch
script to conceal it.

I notice running the script through the python interpreter does not trip
the AV which could mean that the AV does not monitor the file folders.

I'll be testing against McAfee, malwarebytes, Eset, Webroot, and Symantec
Endpoint .

However there are also utilities by NoVirusThanks like OSArmor and
SysHardener which are free as in air, that do monitor sensitive areas.

The trick will be to make lazagne dynamic in that no 2 builds are the same.
Whitehats will need to come up with other methods of identifying it.

I'll keep you posted with any finds.
