### ISSUE TITLE
Chrome passwords

### ISSUE THREAD

**Issue by C10udburst** [AlessandroZ/LaZagne#390]
Hello, 
I'm running chrome version: 73.0.3683.86
I don't get any passwords from it.
Output with -vvv:
`------------------- Google chrome passwords -----------------

[!] Database found: C:\Users\xxx\AppData\Local\Google\Chrome\User Data\Default\Login Data
[!] Temporary db copied: c:\users\xxx\appdata\local\temp\xxx
Fatal Python error: GC object already tracked`

**Comment by billybob3** [comment]
I'm having the same problem.  I'm running Chrome 73.0.3683.103.  Lazagne 2.3.2 finds 4 Chrome passwords and Lazagne 2.4.2 finds no Chrome passwords.  I don't see any error messages at the end of the execution like SwistakPL shows in his report.

**Comment by AlessandroZ** [comment]
@billybob3 I have tested it and it worked for me. Give me the output of: 
`python laZagne.py browsers -google -vv`

**Comment by sllawcj** [comment]
> @billybob3 I have tested it and it worked for me. Give me the output of:
> `python laZagne.py browsers -google -vv`

Using 'lazagne.exe browsers -google -vv'

On laZagne 2.4.2, Chrome 73.0.3683.103, Windows 10.

Repeats the traceback block below for what seems to be each entry in the DB. 

Not sure if related to the original issue, but kinda seems like it to me. 

 ------------------- Google chrome passwords -----------------

[!] Database found: C:\Users\XX\AppData\Local\Google\Chrome\User Data\Default\Login Data
[!] Temporary db copied: c:\users\XX\appdata\local\temp\ilwygzpic
[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x0000030597E18ED8

**Comment by greckko** [comment]
Same issue

**Comment by Papotito123** [comment]
Hello:
I have been struggle with this issue from lazagne v2.4.2.
So I had friendly arguing with the developer.
Few days before the developer gives a little explain about lazagne.exe arch.
So,in short,I had to install Python 2.7.16 x86(I already have the x64 version installed that been used to try to compile but no Chrome accounts recovered ).
And compile the laZagne.py now in this x86 interpreter.The real spot in this issue is not the laZagne.py script.Is that the standalones binaries(and also the compiled) are not full friendly when running in x64 OS because are built using x64 VCR.90 even if x86 are needed for compiling So if you use python x64 to compile lazagne.py, pyinstaller will seek for this VCR.90_amd64 files instead of VCR.90_x86.Due to this,pyinstaller will create lazagne.exe with a bootloader x64 instead of a bootloader x86 that will run fine in x64 OS.
I did compile latest lazagne.py doing like this.It works in Win 1809 x64 .And yes Chrome accounts were recovered.

I hope this helps.

**Comment by Neben66** [comment]
Hello, how compil python with the bash bunny please ?

**Comment by Neben66** [comment]
Hello, how compil python with Bash bunny?

**Comment by AlessandroZ** [comment]
The issue `WindowsError: exception: access violation reading ....` has been fixed. Next release will not have this problem.

**Comment by Neben66** [comment]
when is the other version? Thanks

Ben

Le 3 janv. 2020 à 15:43, AlessandroZ <notifications@github.com> a écrit :

﻿

Closed #390<https://github.com/AlessandroZ/LaZagne/issues/390>.

**Comment by Neben66** [comment]
Did you have a Whatssapp number for text please ? This will be more easy

Ben

Le 3 janv. 2020 à 15:43, AlessandroZ <notifications@github.com> a écrit :

﻿

Closed #390<https://github.com/AlessandroZ/LaZagne/issues/390>.
