### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by byehack** [AlessandroZ/LaZagne#471]
```
Traceback (most recent call last):
  File "c:\Python36\Laz\lazagne\config\run.py", line 45, in run_module
    pwd_found = module.run()  # run the module
  File "c:\Python36\Laz\lazagne\softwares\windows\credfiles.py", line 26, in run
    cred = constant.user_dpapi.decrypt_cred(os.path.join(main_vault_directory, cred_file))
  File "c:\Python36\Laz\lazagne\config\dpapi_structure.py", line 115, in decrypt_cred
    ok, msg = c.decrypt(self.umkp, credfile)
  File "c:\Python36\Laz\lazagne\config\DPAPI\credfile.py", line 95, in decrypt
    cred_dec = CredentialDecrypted(msg)
  File "c:\Python36\Laz\lazagne\config\DPAPI\credfile.py", line 58, in __init__
    DataStruct.__init__(self, raw)
  File "c:\Python36\Laz\lazagne\config\DPAPI\eater.py", line 124, in __init__
    self.parse(Eater(raw, endianness="<"))
  File "c:\Python36\Laz\lazagne\config\DPAPI\credfile.py", line 70, in parse
    self.password = data.eat_length_and_string("L").decode("UTF-16LE").encode("utf-8")  # Unicode
  File "C:\Python36\lib\encodings\utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x24 in position 324: truncated data
```

why `decode("UTF-16LE").encode("utf-8")` used line 70?
what is the problem without `decode("UTF-16LE").encode("utf-8")` in line 70 of `DPAPI\credfile.py`?

**Comment by MyLoginOnGitHub** [comment]
IMHO, the result of `data.eat_length_and_string("L")` is _bytes_. It really needs to decode it to _str_.
The exception occurres in this code because the wrong type of encoding has chosen, so it should be not _UTF-16LE_, but some another. @byehack, can you determine the encoding of result `data.eat_length_and_string("L")` in your case?
Also, I can't undestand too, why to do `.encode("utf-8")`. The result will be _bytes_, but should be _str_.

**Comment by byehack** [comment]
Hello @MyLoginOnGitHub, Thanks for your reply!



> Also, I can't undestand too, why to do `.encode("utf-8")`. The result will be _bytes_, but should be _str_.

yes, me too, for this i said: 
```what is the problem without `decode("UTF-16LE").encode("utf-8")` in line 70 of `DPAPI\credfile.py`?```




> can you determine the encoding of result `data.eat_length_and_string("L")` in your case?

i know 3 way but i don't have time to test them:
1. try with `ISO-8859-1` encoding. i was use it when i had the UnicodeDecodeError like:
`self.password = data.eat_length_and_string("L").decode("ISO-8859-1")`

2. using try/except with `ISO-8859-1`:
```
try:
    self.password = data.eat_length_and_string("L").decode("UTF-16LE")
except UnicodeDecodeError:
    self.password = data.eat_length_and_string("L").decode("ISO-8859-1")
```

3. using try/except with `str` function:
```
try:
    self.password = data.eat_length_and_string("L").decode("UTF-16LE")
except UnicodeDecodeError:
    self.password = str(data.eat_length_and_string("L"))
```
-------------------------------------------------------------------------

i will happy if you can test these solutions.

**Comment by MyLoginOnGitHub** [comment]
Sorry, I could not to repeat this test because I do not know what does credfiles.py searches for. Hense, I do not know how to set credentials for tests.
By the way, I am sure that password (as any another values) should be stored in determinable encoding. So, I think, it is bad way to try to use try-except to determine exact encoding.

**Comment by byehack** [comment]
fixed in https://github.com/byehack/LaZagne
