### ISSUE TITLE
Chrome password is bytes

### ISSUE THREAD

**Issue by dodatdi** [AlessandroZ/LaZagne#488]
I tried on windows with chrome browser and the password output is bytes. I tried decode utf-8 or utf-16 but it didn't work.
Chrome version: 80.0.3987.149

`URL: xxx
Login: xxx
Password: b'v10\x88\xb9\xc8B\x89\x1b\xf1\x89d@\xf3\x141{\xcb\x85\xac\xc83N\xfb\xb0^\x8a\x16W\x98Ig\x9e\xaf\xb9\x13iL\x15\xbcWK\x96'`

**Comment by Papotito123** [comment]
Hello:
This bytes maybe needs to be decrypted with a Masterkey that the program can't identify.
AFAIK is not an error.Is just trying to decrypt a password for other user than the logged one.And to do this you have to do it with some lateral movements.

Look the output and see that Chrome logins for the current logged user is retrieved.
But for others should say something like,can't found MK for guid { xxxxxxxx}.

For seeing what really happens while lazagne is performing,run lazagne all -vvv , to run in debug mode.This way you can look thru the whole process.

**Comment by dodatdi** [comment]
I tried more as you said and got the results
![Capture](https://user-images.githubusercontent.com/30981111/78087816-76278900-73ec-11ea-8156-a1a884f42b69.PNG)
So is there currently no way to see the password? Sorry for my bad English

**Comment by Papotito123** [comment]
Hello:
First of all.
If you are using lazagne.exe binary Chrome passwords will not be retrieved because this issue was resolved some months later.

To retrieve Chrome logins the password needs to be Saved in Chrome browser .

So ,assuming that you are using laZagne.py I certify that Chrome v80 logins are retrieved.

When a line in the -vvv output is color red that means that a mismatch.Otherwise should be in color green.
A mismatch doesn't always means an error.Maybe in your case (as in some cases for me)means trying to perform an action but but a data is not the needed or expected.

Looking these too much red lines PC is not ok for...., maybe is an old OS and maybe with registries issues.

If you even have latest Chrome 80 and password was Saved then logins should be retrieved unless you still have some AV /Defender still enabled while running lazagne.

**Comment by dodatdi** [comment]
Thank you your response!
1. I created lazagne.exe following the link [https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile](url)
2. OS Versions: 17763 ; password was saved in chrome.
3. I turned off windows defender with GPO because if not turned off, AV will detect it.

**Comment by Papotito123** [comment]
Hello:
Build 17763 is Win 1809.I have too.
If you can modify GPO then you doesn't have Home Edition(as I have).
Regarding Defender.
Is a real pain because even disabling Real-Time protection just been connected to Internet could trigger some Cloud protection.Also it has a file analyzer.
So you can try making Exception for lazagne.exe just while doing your testings.
There's some .ps1 to Disable it or toogle Defender.

But,you didn't mention if Chrome logins are retrieved.Did you finally retrieved?

**Comment by dodatdi** [comment]
> But,you didn't mention if Chrome logins are retrieved.Did you finally retrieved?
I don't know if I understand what you mean. The output is the login information with the username is plain text and the password is bytes

**Comment by Papotito123** [comment]
Hello:
Looking for other tools I found one that is only command-line but I managed to go thru the commands stages.
This let me try to understand the stages for finally got Chrome logins in plain-text.

What I understand is this bytes are the login password but in scrambled form due to the need to be decrypted with a Masterkey.And that's the normal process for the logged user while in running OS when running tools to grab Chrome logins ,including lazagne.And this processes should be visible to the logged user with grabbing the username and plain text password.
What is not handled by lazagne(and some other tools) is to decrypt "other non-logged users" Chrome logins due to the fact of the needed Masterkey(that also needs to be decrypted).

So look closely to lazagne output(or the cmd output) and this password "bytes" should be pertinent to other user accounts and not for your "actual logged user".

**Comment by Papotito123** [comment]
Hello:
Also you can read and make this changes(will not hurts,I did it and made a slight change in the .json output).

https://github.com/AlessandroZ/LaZagne/issues/486

**Comment by dodatdi** [comment]
Many thanks for your enthusiastic feedback.

**Comment by dodatdi** [comment]
I tried according to #486 but the result is still the same :(

**Comment by Papotito123** [comment]
Hello:
@AlessandroZ ,I read some info so i'm just to share.
This bytes seems to be the chrome logins unencrypted password blob of the plain-text password.
The v10 in reality is suffix for  v1.0 and meaning is unencrypted form.
So this bytes is showing because with the current user(password) from where lazagne is run, the blob can't be decrypted.
I also found this:
The Nirsoft Chromepass software can read passwords on Chrome from an external hard drive if you remember the windows login password. You need this password:
In order to use this feature, you must know the last logged-on password used for this profile, because the passwords are encrypted with the SHA hash of the log-on password, and without that hash, the passwords cannot be decrypted.
So,the blob is in hand.If password is know ,how can be mixed this conditions in order to get this "other user chrome login" ?.

I'm just asking for this situation that is moving me for some months.

Thanks for keep in touch.
And any idea much appreciated.

**Comment by AlessandroZ** [comment]
Ok I got it, this kind of credential represent an encrypted cred (v10 is a the prefix for encrypted data: 
https://xenarmor.com/how-to-recover-saved-passwords-google-chrome/):

> Now to store the web login password, Chrome encrypts it using AES-256-GCM algorithm with the above master key and 12-byte random IV data. Finally, it inserts signature “v10” to the encrypted password and stores it in above “Login Data” file.

It's like on linux: https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/softwares/browsers/chrome.py#L75

I think an issue occured trying to decrypt the password and it's printed as a raw. Cannot reproduce the error, so cannot help you more.

For your request @Papotito123, to decrypt blob password in a remote hardrive, lazagne use this mechanism as well. Take a look this amazing project DPAPI: https://github.com/dfirfpi/dpapilab and dpapick. It's not easy to understand but you will be able to go deeper into windows password mechanism.

**Comment by dodatdi** [comment]
1. I have tried with nirsoft's chromepass and it works.
2. This is the output after running
![Untitled](https://user-images.githubusercontent.com/30981111/78980335-e39f8c00-7b47-11ea-888f-9ddb2464d2d8.png)

**Comment by AlessandroZ** [comment]
what's your exact chrome version ? 
Try `lazagne.exe browsers -google -vv -password [your user session password]`

**Comment by dodatdi** [comment]
I use chrome version 80.0.3987.149
![Untitled1](https://user-images.githubusercontent.com/30981111/78987261-bb1f8e00-7b57-11ea-8896-444a10e33d30.png)

**Comment by Papotito123** [comment]
Hello:
@dodatdi , as I see 2 system masterkey are OK.
As for me,when using other tools and logins is not retrieved is due user password(or its SHA1) is not the right one or is not retrieved.So for this, shows password in blob encrypted form.
I assumed you have only 1 user account.
Do you test by creating a new windows user(administrator)with latest chrome ?

**Comment by Papotito123** [comment]
Hello:
@AlessandroZ , I used GhostPack/SharpDPAPI and compiled SharpChrome to .exe
Running SharpChrome to .exe from a logged user and knowing the pasword ,I can retrieve the System and Users Masterkeys{GUID) for all users in the running OS(also for not logged) with its matching SHA1 hash.
And then just run the command for the desired not-logged user using its password and the GUID/SHA1 mapping retrieved. And Chrome login is retrieved.
But..... Only works for passwords saved before Chrome 80.
Because for new saved still needs the AES key(Local State) for decryption.

Maybe is out of the issue but just to inform for someine benefit

**Comment by dodatdi** [comment]
After searching, I found this git. [](https://github.com/agentzex/chrome_v80_password_grabber) And it worked. I don't know if there's a difference between the 2 codes. Anyway, thanks a lot for your kind answer

**Comment by Papotito123** [comment]
Hello:.
chrome_v80 was the first tool I tested and worked good.
Maybe you have some registry issues.
Or some AV background process 
Without access to Local State file Chrome logins will not be decrypted,and this file needs some info from DPAPI and the user password.

**Comment by dodatdi** [comment]
How do you compile it? I tried with cx_Freeze it was too heavy (~ 70MB) and pyinstaller got an error:
![Capture](https://user-images.githubusercontent.com/30981111/79063221-82ec8c80-7cca-11ea-97a5-3b3c2c8175e0.PNG)

**Comment by Papotito123** [comment]
Hello:
Teah a face a problem when trying.
It needs a .spec fileto do compiling.
So I used the lazagne.spec and changed as this(delete the .txt ,I have to use to let me upload)

[chromev80.spec.txt](https://github.com/AlessandroZ/LaZagne/files/4467460/chromev80.spec.txt)
 
Then ;
   cmd > cd python-folder > pyinstaller --onefile -w "folder-path-to-chromev80.spec"
 
 In the cmd window take note of the path where the compiled is saved.

Is compiled as .exe but have to be run from a cmd(like lazagne)

**Comment by dodatdi** [comment]
Without a .spec file, pyinstaller will create it itself. After trying with your file, I still get the same error. After searching, I realized that the setuptools were not compatible. So I fixed it. :D
