### ISSUE TITLE
I tried to repackage py into exe, but there are many problems. Is there a help link:)

### ISSUE THREAD

**Issue by 422926799** [AlessandroZ/LaZagne#493]
my After I repackage exe, DLL will be missing in other environment

**Comment by Giawa86** [comment]
I know its problem. But i hope you can solved this problem.🙏

Pada tanggal Sen, 27 Apr 2020 22.26, 九世 <notifications@github.com> menulis:

**Comment by 422926799** [comment]
@Giawa86 I've tried many things, but nothing works，In fact, using Nuitka can be successful, but there will be many dependencies that cannot be integrated  :tired_face:

**Comment by Papotito123** [comment]
Hello:
If you are using python 2 you can encountered some errors.That's why I installed python 3.7.16.If you want a 64 bit .exe you better install python 64 bit.
If you updated python setuptools ,this is causing some issues, so you have to downgrade.
Don't install modules manually. Run the requirements.txt to let install the right modules.
Install via pip, pyinstaller and pywin32 modules.
Some guy mentioned in the past,to copy the 2 .dll files(from system32) mentioned in lazagne.spec, to the lazagne Windows folder,where lasagne.spec resides. 

Install any Visual C++ Redistributable Packages needed(for better compatability install x32 and x64 versions).
I had to install Visual Studio 2016 free version(a real pain to get it to works.).

I had a very big time trying to make all this working.With some trial and error I get it works.

Hope this guide you to the right path.

**Comment by Giawa86** [comment]
I will be check , and i never gone.

Pada tanggal Sab, 2 Mei 2020 04.52, Papotito123 <notifications@github.com>
menulis:

**Comment by 422926799** [comment]
@Papotito123 thank :)

**Comment by AlessandroZ** [comment]
@Papotito123 said it all. Hope it will work for you.
