### ISSUE TITLE
lazagne.py 2.4.4 Firefox

### ISSUE THREAD

**Issue by Papotito123** [AlessandroZ/LaZagne#497]
Hello:
Testing 2.4.4 git I got error in Firefox:

[!] Traceback (most recent call last):
  File "C:\lazaa\Windows\lazagne\softwares\browsers\mozilla.py", line 453, in is_master_password_correct
    cleartext_data = self.decrypt_3des(decoded_item2, master_password, global_salt)
  File "C:\lazaa\Windows\lazagne\softwares\browsers\mozilla.py", line 303, in decrypt_3des
    hp = sha1(global_salt + convert_to_byte(master_password)).digest()
  File "C:\lazaa\Windows\lazagne\config\winstructure.py", line 715, in convert_to_byte
    return string.encode()  # Python 3
AttributeError: 'bytes' object has no attribute 'encode'

Thanks

**Comment by AlessandroZ** [comment]
Hi @Papotito123, 

I didn't test older version because it should have not changed. But I just remembered that the master_password is managed as byte now. Could you please, try it, removing the `convert_to_byte` function: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/mozilla.py#L303

This line: 
`hp = sha1(global_salt + convert_to_byte(master_password)).digest()`

To:
`hp = sha1(global_salt + master_password).digest()`

Hope it will fix the issue.

**Comment by Papotito123** [comment]
Hello:
I did with hp = sha1(global_salt + master_password).digest()  ,and works:

 ------------------- Firefox passwords -----------------

[!] Profile path found: C:\Users\TESTACCOUNT\AppData\Roaming\Mozilla\Firefox\Profiles\ylho7ovy.default
[!] Database empty
[!] Profile path found: C:\Users\TESTACCOUNT\AppData\Roaming\Mozilla\Firefox\Profiles\azatv8ct.default-release
[!] key: b'\------------------------------------------------------\x08'
[+] Password found !!!
URL: https://login.live.com
Login: email@hotmail.com
Password:mypassord

Thanks.

**Comment by AlessandroZ** [comment]
Thanks for your help @Papotito123
