### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Vedant-Bhalgama** [AlessandroZ/LaZagne#535]
Hi! 
I am compiling Lazagne code to EXE using the command you mentioned but when i run the script it says "Failed to execute script laZagne"

**Comment by Papotito123** [comment]
Hello:.
Read #507

I compiled latest lazagne(chromium bug fix) and did well.I ran it and did well.

**Comment by Vedant-Bhalgama** [comment]
Hey! I ran and it went well, but on Windows when i executed the script through i didnt see any kind of output of results. After that i ran the script on kali linux using wine and it worked fine, 

Also I had another doubt that i am trying to obfuscate and compile lazagne code to exe using pyarmor but this error comes up!
It says too big code object to inject into, i think so because of all the different files which are used by laZagne, Is there any solution for this ??


![image](https://user-images.githubusercontent.com/67494275/93361718-ce4f2c00-f862-11ea-98a9-6b4decb480c7.png)

**Comment by Papotito123** [comment]
Hello:
I'm not so skilled.
And I'm not in the stage lever of obfuscating.(I just turn off any AV manually,)

I read about pyarmor and looks interesting.
But in this part ,the program is just saying to pay for unlock character limitation.
I don't know if the lasagne.py and others can be compressed to make it weight less.

**Comment by Vedant-Bhalgama** [comment]
Even after compiling the source code manually Windows Defender is detecting it, Any solution for that?

**Comment by Papotito123** [comment]
Hello:
Compiling doesn't  means stealth.
Antivirus ,including Defender will detect lasagne.
That's why you have to turn it Off to run lazagne

The "pro" way is making is stealth/not detected by obfuscation.I think that's why you are using pyarmor.
But AVs as Defender get triggered by tasks in log events,by suspicious activity,file scanner and others .Also there's something called AMSI that is beyond Defender and can triggered any protection.
One think I know for sure;having an AV(avast,avira,anyone) will make Defender less intrusive. So ,with only disabling-turning OFF the AV will render Defender to "hibernate" and will wakeup in a really critical situation - this is how I run lazagne(also other tools)without being deleted or detected.

**Comment by Papotito123** [comment]
Hello;
I tested pyarmor with laZagne.py and this  "too big code object ,,." ,  is a trial limitation.
Even obfuscating only laZagne.py , the trial limitation arise when trying to compile via pyarmor.

If you compile laZagne.py with the way @AlessandroZ instruct, the lazagne.exe will run good with Avast turned ON(Defender will be in some "hibernation").
I tested .
But if you have only Defender then you have to turn it OFF.There's some tools/.ps1 to do this.
Or whitelist the lazagne.exe in Defender(and there's way to do it) , before running.

**Comment by Vedant-Bhalgama** [comment]
Is there any way we can turn off Windows Defender remotely? I know a command-line argument for it but it requires admin privilege. Any help with that?

**Comment by Papotito123** [comment]
Hello:
Of course should be.
But I'm more into access information for when in trouble situations and not to access remotely.

Also with respect to the developer, this is out of the scope of the issue.
I jump to the post because at my beginning, I had trouble to successfully compile.

That's my spirit.
