### ISSUE TITLE
Lazagne finds only my WIFI password, but it does not find my other passwords, it says then password not found.

### ISSUE THREAD

**Issue by Sprifanco** [AlessandroZ/LaZagne#548]
I have the latest lazagne software, but it does not work verry well. It only finds my wifi passwords and nothing else.

**Comment by Papotito123** [comment]
Hello:
If you are using the lazagne 2.4 3 standalone then this is not updated for the new chrome and Firefox codes.
You have to use Python(at least v.3.5) to run and compile the latest lazagne code.
With pyinstaller you can compile to lazagne exe.
This works well.

**Comment by Sprifanco** [comment]
I have installed python, but i dont know how i can compile it. Is there a tutorial for it?

**Comment by Sprifanco** [comment]
Another qeustion, how can i get the password from my laptop with LaZagne.exe? If i do the command it shows me the wifi,Mscache,Hashdump and Lsa_secrets passwords, but i cant see the windows password from my laptop.Thats the reason i installed LaZagne.exe

**Comment by Papotito123** [comment]
Hello:
You have to:
Open a cmd(Run as Administrator).

   cd "python folder"

Install lazagne requirements:important 
   pip install -r "path-to'\requirements.txt"

Install pyinstaller:use to compile to exe
   pip install pyinstaller

Before compiling laZagne.py you have to run it first because will create some files:
   pip "path-to-laZagne.py"

Run laZagne.py all commands:
  "path-to-laZagne.py" all

After finishes,to compile to .exe:
  cd "path-to-pyinstaller" 

  pyinstaller --onefile "path-to-laZagne.py"

Look carefully to see the path where lazagne.exe will be saved.

Test your lazagne.exe.

For troubleshoot or see running in details, run as:

  lazagne.exe all -vvv

Did you know that Windows user password is not kept in memory from Win 8.1?
So to grab user password you have to modify registry.
But you can grab logged user NTLM/SHA1 hashes and try to decrypt it.

Latest laZagne.py can recover latest Chrome,Firefox builds.

**Comment by Sprifanco** [comment]
Oke thx for explaining, do you know a good hash decrypter or something that decrypts hashes?

**Comment by Papotito123** [comment]
Hello:
This is not a simple easy way.
You could need some hardware(16gb RAM,8core CPU,a good video card to use the GPUs) and a pretty big dictionary(some 100s gigabytes) and some time(between hours to years).

Just googled to recover windows user password and tools to decrypt NTLM hashes.
Is not wasted time because you will learn some about user password.

**Comment by Sprifanco** [comment]
Do you maybey know how can i find the password from my laptop on my laptop? My boss challenged me to find his password, butt i saw that LaZagne.exe cant find it, so maybey you know?

**Comment by BAMBINO559** [comment]
I am also having this issue. I have tried many different ways to get this to work for over a day with no luck. I followed the instructions @Papotito123 gave above to create the .exe file. When I run the .exe file via the command line, I get an error:

SyntaxError: Non-UTF-8 code starting with '\x90' in file C:\Python\Python39\Scripts\dist\laZagne.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details 

If possible, someone should write better instructions on the installation process. It is rather confusing at the moment. @Papotito123 mentioned "You have to use Python(at least v.3.5) to run and compile the latest lazagne code." Thing is, the 'instructions' here (https://github.com/AlessandroZ/LaZagne/wiki/Requirements) mention "Python 2.7 is needed." 

Any help regarding any of this would be much appreciated.

**Comment by Papotito123** [comment]
Hello:
lazagne code is not compatible with python 2 from last year.So ,install python 3.7 at least(that's what I have).
This error of python bytes is due to compatibility.Not more.
python str UTF-8 UTF16LE are not managed in the  same way in pyyhon2 and python3 in a code.
The dev take some time until make the code fully compatible with python 3.Now ,lazagne code doesn't works with python2.That's it.

If my explanation is so confusing for you, look at some Closed issues and will find some others(but  you will see that some of them were posting by me).

When I came to lazagne tried to use laZagne.py I got this this kind of errors ,so I had to learn to install python mostly by looking in YouTube and in some other apps websites(by taking advantage that explain how to install python)..Then when errors still,I faced the wall.Why I got this error? Because I installed python3 and the code were still exclusively for python2.

Hope now you can move to a better direction.

**Comment by justice-oguche** [comment]
Pls I don't know why lazagne doesn't retrieve passwords for for latest versions of chrome
