### ISSUE TITLE
Hello everyone! Can lazagne work on android? Or does anybody knows how to run similar task on android devices?

### ISSUE THREAD

**Issue by nini884** [AlessandroZ/LaZagne#554]
Hello everyone! Can lazagne work on android? Or does anybody knows how to run similar task on android devices?

_Originally posted by @iwundu in https://github.com/AlessandroZ/LaZagne/issues/21#issuecomment-549787583_

**Comment by FloatKey** [comment]
Yes and no.
Its a quite difficult because most of Lazagne fonctions work with Linux specifics directories/libraries.
Even if you fix this problem, Android will ask root acces for almost everything.

I think the easiest way to make lazagne works on Android is adapting fonctions and then to compile the python code to an APK to run it on any android device without using terminal emulator.
