### ISSUE TITLE
Failed to extract IE password on WIN10??

### ISSUE THREAD

**Issue by simonpunk** [AlessandroZ/LaZagne#63]
First, I'm very thankful that you have created this such amazing tool. it does a magic work here.

But I get an error when retrieving the IE password on my win10 with IE version: 11.494.XXXXXXX.

it says:

> ------------------- Internet Explorer passwords -----------------
> 
> [DEBUG] (2, 'RegOpenKeyEx', 'The system cannot find the file specified.')
> 
> No password stored.
> The registry key storing the ie password has not been found.
> Key: Software\Microsoft\Internet Explorer\IntelliForms\Storage2
> 

So I go to look at my regedit, and seems my key path is 
> Software\Microsoft\Internet Explorer\IntelliForms\FormData

But it tested successfully on win7 with IE version: 11.0.9600.XXXXXXXX

So, any ideas?

**Comment by AlessandroZ** [comment]
Hi, 

The credential manager is different between Windows 7 and Windows 8 (the structures are not the same). So using python, I find an easy way to retrieve credentials from the credential manager of Windows 7 but I cannot manage to do it for Windows 8. So my tool does not manage the credential manager for higher version of Windows 7. 
Internet explorer uses two ways to store its credentials. Before Windows 8, an hash of the password was stored on the registry key "Software\Microsoft\Internet Explorer\IntelliForms\Storage2". 
But since Windows 8 and IE 11, passwords are stored on the credential manager. So the tool will not be able to retrieve it. I hope to do it one day. 
If you want to dump passwords of the credential manager on Windows 8, you could use the awesome tool called mimikatz : https://github.com/gentilkiwi/mimikatz

Have a great day.

**Comment by simonpunk** [comment]
@AlessandroZ 
Hi, thanks for your reply, I know what you mean now. But right now I just got another tool called iepv.exe from nirsoft.net , and it did succeeded to retrieve the password for me without the system privilege and not being detected by AV. But I am not sure whether it uses the same way as mimikatz or not as I know mimikatz needs to work with system privilege.

Anyway, thanks for your great work here, and I just wrote up a simple post module script for metasploit, it will simply upload the tool, execute it, download the password file, and then clean up itself. Now I do think it saves a lot of time and steps as it only takes no more than 1 minute to retrieve all possible passwords in the computer. 

So, it would be so amazing if your tool can be integrated with metasploit.

**Comment by AlessandroZ** [comment]
Hi, 

Sorry for my late answer, I'm in holidays right now. 
I will take a look about the iepv.exe tool, I have no idea how it works. I could be interesting to implement it. 

For your post exploitation module, I didn't find it, I don't know if you released it publicly. 

Right now, I'm working on another project called pupy (https://github.com/n1nj4sec/pupy/) and the laZagne module will be executed directly on memory. The python files will be interpreted from memory, so it will avoid writing the binary to the disk. If one day laZagne is detected by AV, this technic will bypass its detection. 

Have a nice day. 

Alessandro

**Comment by AlessandroZ** [comment]
My last commit manages the Internet Explorer passwords stored on the Windows vault (credential manager).  It does not require admin privileges.
