### ISSUE TITLE
Error decoding code?

### ISSUE THREAD

**Issue by Krofolin** [AlessandroZ/LaZagne#74]
It gets the email or username, but when it comes to the password it says "Error decoding code" or leaves empty space. It only gives me about 3-4 results of which not one has a password.

**Comment by AlessandroZ** [comment]
This is not an error, it has been catch by a try / except statement. However, it happens when trying to decrypt passwords stored on the credential manager. Some passwords are not managed such as Outlook Exchange which the password returned in not correct or this kind of error message could happen. Some kind of passwords are not well managed. 
Before to close this issue, could you give me the exact kind of software the password is not decoded / decrypted to give a look. 

Thank you.

**Comment by Krofolin** [comment]
Well in my case it just gives me 4 results of which one is skype where it gives me a "hash_md5" code, the next is GoPro_Desktop_App (Error decoding the password), Microsoft_PaidConnectivity_Wifi_AccessToken (Error decoding the password) and then MicrosoftAccount (password is empty)

**Comment by BobPeterson** [comment]
For the skype hash is a normal behaviour, the password is not stored in plaintext but as a hash. So only using brute force or dictionary attack could help you to retrieve the password. 
For the rest, some passwords are not well managed yet. Moreover, sometimes some information are printed whereas no passwords are stored. So it could be a false positive or an error. I have to investigate these tools. 
Thank you !
