### ISSUE TITLE
Main function not exist?

### ISSUE THREAD

**Issue by Omardavinci** [AlessandroZ/LaZagne#78]
Sorry for this but why main function is not included?
C:\Python27\python.exe: can't find '__main__' module in 'laZagne'

I need to include or set other function? i tried this command

python laZagne --version

and any command show me main i think because the main function doesnt exist idk

**Comment by AlessandroZ** [comment]
No I think it's because you are in this directory: https://github.com/AlessandroZ/LaZagne/tree/master/Windows
And 2 files are called lazagne (in windows it's case insensitive) so you have to specify the correct file adding the extension. Maybe it was not a good idea to add two files with the same name (it's my fault). 

Try: 
`python laZagne.py --version`

Let me know and close the issue if it's ok for you.

**Comment by Omardavinci** [comment]
ok it's solved i forgot .py
