### ISSUE TITLE
Google Chrome

### ISSUE THREAD

**Issue by chafik0** [AlessandroZ/LaZagne#9]
Well, first, thank you for the great job !

I'm having an issue with google chrome on windows 7.
I'm getting this message: [INFO] Google Chrome not installed.

According to LaZagne-master\Windows\src\LaZagne\softwares\browsers\Chrome.py file, the path isn't recognized.

path_Win7 = os.environ.get('HOMEDRIVE') + os.sep + os.environ.get('HOMEPATH') + '\Local Settings\Application Data\Google\Chrome\User Data\Default\Login Data' doesn't seem right on my computer.

The correct path for my Login Data file would be:
'C:\Users\%USERNAME%\AppData\Local\Google\Chrome\User Data\Default\Login Data'

Thank you ;)

**Comment by AlessandroZ** [comment]
Hi, 
Thank you for your feeback. Your problem is quite strange because you were right about where the occurs but I put 2 differents path to find the Chrome Database: 
* path_Win7:
``` 
C:\Users\<USER>\Local Settings\Application Data\Google\Chrome\User Data\Default\Login Data
```
* path_XP
```
C:\Users\<USER>\AppData\Local\Google\Chrome\User Data\Default\Login Data
```
Your path is as the XP path (I thought it was only for XP, but I was wrong). However, I check both path. 
I have made a little change (I cannot be sure it will correct your problem), if you could download again the tool and try it. I hope it will work. 

If not, could you please give me more information (the "Login Data" database exists on your computer, it is empty, etc.). 

Thank you for your help.

**Comment by BeanBagKing** [comment]
It looks like I'm having the same issue. I have a Login Data file in both locations, which I believe are symlinked, so that's expected. I have data in that file and have confirmed with an SQLite browser that it contains a blob of login information. However, when running the LaZagne standalone windows exe (0.9.1) I get the message "Google Chrome not installed".

Has the change you made been incorporated into the 0.9.1 standalone release?
