### ISSUE TITLE
LaZagne 2.0 - Windows 10 - LaZagne freeze when looking for KeePass

### ISSUE THREAD

**Issue by jboss38** [AlessandroZ/LaZagne#97]
Hello,

When runing LaZagne with all modules, the program freeze at KeePass. Runing without admin priv.
Detail Error:

------------------- Keepass passwords -----------------

Password not found !!!
Get-Process: Impossible de trouver un processus nommé « KeePass ». Vérifiez le nom du processus et appelez de nouveau l'applet de commande.

Traceback (most recent call last):
  File "laZagne.py", line 116, in launch_module
  File "lazagne\softwares\memory\memorydump.py", line 70, in run
  File "lazagne\softwares\memory\memorpy\MemWorker.py", line 108, in mem_search
  File "lazagne\softwares\memory\memorpy\WinProcess.py", line 197, in iter_region
  File "lazagne\softwares\memory\memorpy\WinProcess.py", line 169, in VirtualQueryEx

**Comment by AlessandroZ** [comment]
Hi, 

The problem is not in the keepass module because, the module ended correctly. The following module "memorydump" will retrieve passwords from regex in browser memory. It could take a while so be patient and it will finish even if it takes time. More your process memory will be large, more it will take time. 

- To understand what I'm saying, close every browser processes running (firefox, chrome, ie, etc). and launch lazagne again. 

- Another tests that you can do, is to close every browser processes, launch a new one (firefox or another one), load to gmail without saving the password and launch lazagne again. Because of the process is quite new, it should not take too long.

**Comment by jboss38** [comment]
ok i got it !

Sry my bad :/
